### ISSUE TITLE
Incompatible with BetterWithMods' Hardcore Hunger feature

### ISSUE THREAD

**Issue by Hastling** [squeek502/SpiceOfLife#102]
The crash is limited only to the client connected to the server and occurs when eating any food item. http://pastebin.com/qXjkjY4e

Edit: It turned out to be an incompatibility from BetterWithMods new hardcore hunger, once disabled via the config the crash stopped.

**Comment by squeek502** [comment]
BWM added support for AppleCore, so this should be fixed in recent versions
