### ISSUE TITLE
[1.10.2] Maximum eating duration sets the minimum as well

### ISSUE THREAD

**Issue by ulk-underscore** [squeek502/SpiceOfLife#103]
Is set food.eating.duration.max to 128 in the config. Now even the first food I eat in a newly generated world will take a long time to eat (presumably the 128).
I also changed the config to (1) not affect hunger and (2) affect saturation and (3) use the amount of hunger restored instead of the amount of food eaten. So it might occur only with this configuration.
[Full config](http://pastebin.com/0tkRCYiL)

**Comment by squeek502** [comment]
Wow, good catch, I totally messed this one up and it's using the config option as a _minimum_ instead of a maximum. 😢

**Comment by UndeadZeratul** [comment]
It looks like you fixed it in the 1.7.10 branch; the 1.9.4 (and thus 1.10.2) branch still has it as max()

Thanks for fixing it in the 1.7.10 branch though!  I might actually put the config back now that I know it was broken and is now fixed :smiley:

**Comment by squeek502** [comment]
Yep, will merge it through and release new versions for each MC version when I get a chance.
