### ISSUE TITLE
Add count variable to formula that ignores food groups

### ISSUE THREAD

**Issue by squeek502** [squeek502/SpiceOfLife#106]
From [CurseForge](https://minecraft.curseforge.com/projects/the-spice-of-life?comment=36):

> With food groups enabled, I can get how many times any-thing from $group was eaten, but I cannot get how many times any one particular thing was eaten. I would like to have access to the individual tracks at the same time as the food groups, if that's not going to be tricky to implement.

Already have [a method for it](https://github.com/squeek502/SpiceOfLife/blob/1.9.4/java/squeek/spiceoflife/foodtracker/FoodHistory.java#L109-L112), just need to expose it as a variable to the formula.

**Comment by Syndaryl** [comment]
Hurray!
