### ISSUE TITLE
[1.10.2 / Request] Hunger Persistence Upon Death

### ISSUE THREAD

**Issue by Endgineer** [squeek502/SpiceOfLife#109]
In MC 1.7, TiC had a side-feature (config file option) that basically made hunger levels (minimum of 3) persist on death; which meant that anyone dying with a hunger level below 3 spawned with a hunger level of 3 and anyone dying with a number above that spawned with that number. This feature basically stopped players from killing themselves to avoid eating since they'll eventually have to live permanently with 3 hunger (no sprint).

Upon moving into 1.10.2, TiC refocused (like many other mods) and the mod dev decided not to include this feature anymore since it's not within the scope of TiC. In turn, I've noticed that many lazy players began to kill themselves to avoid the repercussions of "not eating", which basically removes purpose food, hunger, farms, Spice of Life, and everything related to those things.

I've already posted an issue on the TiC GitHub and they've suggested that I either open an issue on Quark or Spice of Life; and seeing as this is the mod that directly influences hunger, it would be the better choice. I humbly suggest that you consider this feature, since players kill themselves primarily to counter Spice of Life (seeing as it forces them to eat many different kinds of food) and that sucks. :C

**Comment by squeek502** [comment]
This doesn't seem like it'd be too hard to do, but I'd be tempted to split it into a separate mod.

**Comment by Endgineer** [comment]
Either way, please consider it! As I said, some people unfortunately find ways around amazing mods like yours and it's sad to see that the mod is basically useless in such a case. People get SoL to make the game more hardcore in a way and it's annoying to see people work around that. :S

**Comment by Terrails** [comment]
Well I was just about to make the same feature request. This kind of feature is really needed for harder modpacks.

**Comment by squeek502** [comment]
@Endgineer, @Terrails I implemented this as its own mod called Hunger Persistence:

https://github.com/squeek502/HungerPersistence

Can download it here:
https://github.com/squeek502/HungerPersistence/releases
https://minecraft.curseforge.com/projects/hunger-persistence
