### ISSUE TITLE
The Cake is a Lie

### ISSUE THREAD

**Issue by eyamaz** [squeek502/SpiceOfLife#11]
And ignores all the things because it is a TE. This is an easy way around SoL and is in EVERY pack since, of course, its vanilla. Any ideas if an ASM can fix this?

**Comment by squeek502** [comment]
Yeah, I'll close this loophole. Thought about it before, but never ending up doing anything about it.

**Comment by anion155** [comment]
HarvestCraft cakes still lets me cheating ))

**Comment by squeek502** [comment]
@anion155, that will need to be solved by AppleCore. Created an issue here: https://github.com/squeek502/AppleCore/issues/32
