### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Zekken01** [squeek502/SpiceOfLife#111]
Idk what's going on here, please help.
https://paste.ee/p/4Q5eV

**Comment by squeek502** [comment]
AppleCore (required by Spice of Life) is currently incompatible with Forge 2123. See https://github.com/squeek502/AppleCore/issues/80

**Comment by squeek502** [comment]
Should be fixed in AppleCore v2.1.0: https://github.com/squeek502/AppleCore/releases/tag/v2.1.0
