### ISSUE TITLE
I cannot get the custom script to work

### ISSUE THREAD

**Issue by Boter316** [squeek502/SpiceOfLife#115]
I cannot find a tutorial anywhere, I wish to make some foods that do not have diminishing returns, could someone provide an example for me? (both json and how the config would look in order to enable), what should I put into "food groups" for it to see my json?

**Comment by squeek502** [comment]
Saving this as `test-blacklist.json` in `config/SpiceOfLife` should exclude apples from diminishing returns (no changes to SpiceOfLife.cfg needed):

```json
{
	"food": {
		"items": [
			"minecraft:apple"
		]
	},

	"blacklist": true
}
```

See `config/SpiceOfLife/example-food-group.json` for more documentation.
