### ISSUE TITLE
[1.10.2] Lunchbox dupe (server side)

### ISSUE THREAD

**Issue by xSparky911x** [squeek502/SpiceOfLife#119]
In a multiplayer server, when scrolling food from the Lunchbox the game does a temporary freeze and kicks you from the server but does not crash the game. When you join back in you have an extra food item in your inventory and still the same one in the Lunchbox. Not sure if this is caused by Spice of Life or Inventory Sorter based on the log. Does not seem to happen in single player

Forge: 2221
Inventory Sorter: 0.10.5+46
The Spice of Life: 1.3.7

**Comment by squeek502** [comment]
Any chance you could post the log (or just the stacktrace of the error)?

EDIT: Nevermind, found it linked in the Inventory Sorter issue (https://github.com/cpw/inventorysorter/issues/34): http://pastebin.com/PhMyJS4L

**Comment by squeek502** [comment]
It's unclear to me why the malfunctioning code is being executed, as it should be skipped on the server. The [code in question](https://github.com/squeek502/SpiceOfLife/blob/1.9.4/java/squeek/spiceoflife/inventory/FoodContainerInventory.java#L30-L33):

```java
if (FMLCommonHandler.instance().getEffectiveSide() == Side.CLIENT)
{
	findMatchingClientItemStack();
}
```

**Comment by squeek502** [comment]
I am unable to reproduce this locally--the code posted above is working as expected for me.

**Comment by xSparky911x** [comment]
This only happens to me on a server, not single player if that matters

**Comment by squeek502** [comment]
Yeah, was testing it on a server, still no luck. Something really strange has to be happening because there's no way `FMLCommonHandler.instance().getEffectiveSide()` should be `Side.CLIENT` on a server as far as I know.

**Comment by xSparky911x** [comment]
Hmm wonder what I should do lol. Does Inventory sorter have anything to do with it?

**Comment by squeek502** [comment]
I'm not sure. If you can trigger the error consistently, try putting this version of Inventory Sorter on your server and see if that fixes it:

[inventorysorter-1.10.2-0.10.5+test.jar](https://www.ryanliptak.com/misc/inventorysorter-1.10.2-0.10.5+test.jar)

**Comment by xSparky911x** [comment]
ok will install it right away and reboot the server. The error is consistant for me and a fellow player as of now

**Comment by xSparky911x** [comment]
Ok that version fixed it. Going back to the old one now to see if error returns

**Comment by xSparky911x** [comment]
Confirmed. Version 0.10.5+46 will kick me when scrolling food from the Lunchbox as well as the Lunchbag

**Comment by squeek502** [comment]
Alright, thanks for the confirmation. Will submit a pull request to Inventory Sorter with the fix.

**Comment by xSparky911x** [comment]
And thank you for the fast fix even though it was someone else's mod :) I am using your mod in my Apocalyptic pack and it fits very well. Keep up the awesome work!
