### ISSUE TITLE
Brain jerky restores more than it should

### ISSUE THREAD

**Issue by Wingyl123** [squeek502/SpiceOfLife#121]
In Agrarian Skies, for whatever reason, while the tooltips for Brain Jerky (from Witching Gadgets) say it should restore around half a shank or so, it actually restores its default value.
I'm not sure if this is for balance reasons (making you have to wait longer between eating aspect-point-giving, warp-free brain jerkies) or not.

**Comment by squeek502** [comment]
- If you're talking about Agrarian Skies for Minecraft 1.6.4, then that version of TSoL is no longer supported
- If you're talking about Agrarian Skies 2 for Minecraft 1.7.10, then that probably means Witching Gadgets needs to make sure that [its food is compatible with AppleCore](https://github.com/squeek502/AppleCore/wiki/Integrating-food-items-with-AppleCore).
