### ISSUE TITLE
Automatically Adding To Lunch Box

### ISSUE THREAD

**Issue by HypnoPants** [squeek502/SpiceOfLife#122]
Supposedly if you right click the lunch box in your inventory it will add items into it automatically, it doesn't seem to be working for me.

**Comment by squeek502** [comment]
If you right click *on* an inventory in the world (like a chest) with the lunch box in your hand, it will add items from the chest into the lunch box.

**Comment by HypnoPants** [comment]
oh! awesome, thanks!! :)

although... I just tried it on 6 64 stacks of different foods... and all of them got added to the lunch box, but the 64 stacks all disappeared, essentially deleting a lot of the items.

**Comment by squeek502** [comment]
What version of the mod are you using, and which Minecraft version are you playing?

**Comment by squeek502** [comment]
Didn't realize you opened a new issue. Moving this discussion to #123

**Comment by HypnoPants** [comment]
heh sorry, figured it should've been seperate as it in itself was a bug
