### ISSUE TITLE
Adding to Lunch Box from Chest

### ISSUE THREAD

**Issue by HypnoPants** [squeek502/SpiceOfLife#123]
It adds food automatically to the lunch box however...

Let's say you have 6 stacks of 64, it adds 2 of each food item, but the rest of the food in the chest is deleted. As if you had added 64 of each food item to the lunch box, but only ended with 2 of each with the rest just disappearing.

**Comment by HypnoPants** [comment]
currently I just switched the max stacks to 64, but that kinda ruins the whole difficulty thing :P

**Comment by squeek502** [comment]
What version of the mod are you using, and which Minecraft version are you playing?

**Comment by HypnoPants** [comment]
SpiceOfLife-mc1.11.2-1.3.8
AppleCore-mc1.11.2-2.1.1

Minecraft 1.11.2

**Comment by squeek502** [comment]
This is a new bug introduced in the 1.11.2 version. Will try to get it fixed soon.

**Comment by nephatrine** [comment]
Just fyi this issue still seems to exist. Is this going to be resolved for 1.11.2?

**Comment by squeek502** [comment]
Yeah, I really messed up the 1.11.2 port and have been dragging my feet on getting it fixed, sorry. Will have another go at fixing it now.

**Comment by squeek502** [comment]
Should be fixed in the next version.
