### ISSUE TITLE
Separate lunchbox mod

### ISSUE THREAD

**Issue by adegarimore** [squeek502/SpiceOfLife#125]
It would be great if I could add the lunchbox to my modpack without adding all the fancy spice of life stuff. Would you could consider separating Spice of Life and the Lunchbox?

**Comment by adegarimore** [comment]
Oh ya. Were talking about MC 1.10.2 :)

**Comment by squeek502** [comment]
You can basically already do this by setting the config option "food.modifier.enabled" to `false`

**Comment by adegarimore** [comment]
Alrighty thanks.
