### ISSUE TITLE
Coffee from Actually Additions not working with Spice of Life

### ISSUE THREAD

**Issue by Redlotus99** [squeek502/SpiceOfLife#127]
I assume this may be on the Actually Additons side, but coffee from Actually Additions doesn't adhere to the Spice of Life rules on food. Is there anything that can be done on the Spice of Life side or I can add server side?

**Comment by squeek502** [comment]
Direct the Actually Additions mod authors to: https://github.com/squeek502/AppleCore/wiki/Integrating-food-items-with-AppleCore
