### ISSUE TITLE
Diminishing returns resets every time a world is loaded(SpiceofLife)

### ISSUE THREAD

**Issue by XygenSS** [squeek502/SpiceOfLife#128]
After shutting down Minecraft and then reopening the world, the diminishing returns feature resets and displays 'Diminishing Returns starts after eating any food n more times' when cursor is placed over any food item. This is able to be reproduced.

**Comment by squeek502** [comment]
Been meaning to look into this, seems like I messed something up in the 1.11.2 port.

**Comment by squeek502** [comment]
Should be fixed in the next version.
