### ISSUE TITLE
Suggestion: Treat cakes the right way

### ISSUE THREAD

**Issue by saibotk** [squeek502/SpiceOfLife#130]
Cakes in **Pam's Harvestcraft** currently aren't affected by SOL, this can be abused.

I hope you can explain, why the cakes are not included, wether it is because of the implementation or it was just unnoticed.

Thank you for your awesome mod, keep up the good work ;)

**Comment by squeek502** [comment]
Block-based foods don't work like other foods, and last I checked Pam's uses completely custom code for its cakes so I'd need to add special support for that in AppleCore, which I never got around to doing. See: https://github.com/squeek502/AppleCore/issues/32

It's not very likely that this will be fixed any time soon, unfortunately.

**Comment by squeek502** [comment]
This will now be up to mods to add support for, see [this wiki article](https://github.com/squeek502/AppleCore/wiki/Integrating-food-items-with-AppleCore#block-based-foods-like-cake) for instructions.
