### ISSUE TITLE
Crash when attempting to move open lunch box

### ISSUE THREAD

**Issue by Noobulus** [squeek502/SpiceOfLife#137]
The game crashes when you attempt to move an open lunch box while the GUI is open. A safeguard against this, such as whatever TE uses for its sachels, would make the issue nonexistent.

**Comment by squeek502** [comment]
This seems to be a regression in The Spice of Life for recent versions of MC (works fine in MC 1.10.2 and earlier). Will look more into it, thanks for reporting.

**Comment by squeek502** [comment]
Should be fixed in 1.3.12
