### ISSUE TITLE
Desync when shift+clicking items into the food container

### ISSUE THREAD

**Issue by Xiaminou** [squeek502/SpiceOfLife#139]
When you open the food container and use shift+click items (is it vanilla or from inventory tweaks?) it does put items into the food container but does not show it (desync). Re-opening your inventory or the food container will show the correct location of the items.

Minecraft: 1.12.2
Forge: 2525
Mods: [list.txt](https://github.com/squeek502/SpiceOfLife/files/1444455/list.txt)

**Comment by squeek502** [comment]
Probably a similar regression to #137. Will take a look, thanks for reporting it.
