### ISSUE TITLE
[Suggestion]Biscuit of Totality in Botania will not be affected

### ISSUE THREAD

**Issue by SihenZhang** [squeek502/SpiceOfLife#142]
As is known, Biscuit of Totality in Botania is a way to avoid The Spice Of Life. I think that's NOT what a modpack maker want. 

Recently, AppleCore-mc1.12.2-3.1.0 adds some features about edible blocks like cakes. Maybe(?) cakes will be affected by The Spice Of Life now.

So, when Biscuit of Totality in Botania can be affected?

**Comment by squeek502** [comment]
Looks like the Biscuit of Totality adds a potion effect. That's not something I'm planning on making The Spice of Life affect.

For cakes, mods would have to [make their cakes compatible](https://github.com/squeek502/AppleCore/wiki/Integrating-food-items-with-AppleCore#block-based-foods-like-cake)--right now only the Minecraft cake is affected (relevant issue: https://github.com/squeek502/SpiceOfLife/issues/130)
