### ISSUE TITLE
[1.12.2] Crash when open lunch box

### ISSUE THREAD

**Issue by KorDum** [squeek502/SpiceOfLife#143]
https://gist.githubusercontent.com/KorDum/5d32319b82704ae919b30c3b52fd6842/raw/3dda02e217b9cf18458a20e8b1b4df6a519d92e0/gistfile1.txt

**Comment by tfox83** [comment]
can confirm getting same crash from multiple beta testers on the FTB Team:

(From my issue tracker)

clicking on lunch bag while open crashes client
i clicked on it to see what would happen it crashed here is the crash report https://pastebin.com/cJ37j5SW

**Comment by squeek502** [comment]
Should be fixed in 1.3.12
