### ISSUE TITLE
[1.12.2] Server Crash

### ISSUE THREAD

**Issue by BuilderDan** [squeek502/SpiceOfLife#146]
**Version Information**

Minecraft 1.12.2
Forge: forge-1.12.2-14.23.3.2655-universal.jar
SOL: SpiceOfLife-mc1.12-1.3.11.jar

**Report Information**
This is the crash report:
https://pastebin.com/LXM7eu1d
Not sure what occurred in the game for the server to crash, but it is obviously something to do with Spice Of Life and Lunchboxes I would assume.
My Config:
https://pastebin.com/0bJMNRRa
Do note that I am running other mods as you can tell in the crash report, but I highly doubt they're the cause of the crash, I believe it is isolated to multiplayer and Spice Of Life.

**Steps to Reproduce**
Play on a server with SOL installed and interact with lunchboxes until a crash occurs.

If any other information is needed then I will try my best to gather it.

**Comment by P3rf3ctXZer0** [comment]
Sorry I meant a while back to report this about a month ago but forgot to.

**Comment by Konngitas** [comment]
I remember what caused my crash, it was when I clicked on the lunch box while it was open

**Comment by P3rf3ctXZer0** [comment]
me too.

**Comment by squeek502** [comment]
Should be fixed in 1.3.12
