### ISSUE TITLE
Fruits showing as "raw meat"

### ISSUE THREAD

**Issue by asphaltbuffet** [squeek502/SpiceOfLife#154]
Bush-type fruits (blueberry, raspberry, etc) from the Natura mod are showing an additional food category of "Raw Meat". As a result, they can't be used for fruit baits.

![2018-08-18_15 30 54](https://user-images.githubusercontent.com/30903912/44308366-04670c80-a37a-11e8-89e5-256c1d911ee5.png)
![2018-08-18_15 31 00](https://user-images.githubusercontent.com/30903912/44308367-04670c80-a37a-11e8-80bc-30c3f5bb9f07.png)
![2018-08-18_15 31 08](https://user-images.githubusercontent.com/30903912/44308368-04670c80-a37a-11e8-86d5-3598becf3715.png)

**Comment by squeek502** [comment]
Sounds like something you should report to the modpack you're using. The mod doesn't add food groups by default.
