### ISSUE TITLE
Lettuce Crash

### ISSUE THREAD

**Issue by Hexidecimark** [squeek502/SpiceOfLife#166]
Occurred on a SpongeForge server today. Running as food mods Pam's, Spice of Life, and Spice of Life: Carrot edition, of which it seems Spice of Life was the likeliest culprit, as it adjusts food saturation. This is an exceedingly uncommon issue that has happened only one other time in testing, though no logs were captured from the event.

The issue was eventually solved when the player dropped the erroneous uneaten lettuce, which otherwise caused the same error several seconds after he logged in.

The player's initial error log can be found at:
https://mclo.gs/H65aoPN
For readability, and has also been attached for longevity.
[latest (5).log](https://github.com/squeek502/AppleCore/files/5147589/latest.5.log)

The error log when trying to log back in can be bound here:
https://mclo.gs/N0RPwCs
And is also attached:
[2020-08-30-3.log](https://github.com/squeek502/AppleCore/files/5147598/2020-08-30-3.log)

**Comment by squeek502** [comment]
- This is unrelated to AppleCore, so I've transferred it to the Spice of Life repo
- The error in the `.log.gz` file is: `Function IF expected 3 parameters, got 1` coming from your `food.modifier.formula` config setting. Could you post what you're using for that?
- Are The Spice of Life and The Spice of Life: Carrot Edition meant to be compatible? They are entirely different mods, despite the confusingly similar names.

**Comment by Hexidecimark** [comment]
It must be the modifications to the formula I've made then. The two are fully compatible as neither interferes with the other at any level. 
On closer inspection, it seems that my syntax for an IF statement was off, so AppleSkin triggered the error when it called for the value of the food, which called for the second condition, which I had not given.
