### ISSUE TITLE
Add a lunch box

### ISSUE THREAD

**Issue by squeek502** [squeek502/SpiceOfLife#25]
See [this reddit comment chain](http://www.reddit.com/r/feedthebeast/comments/2eydz5/thoughts_on_spice_of_life_mod/ck47i4v)

> Yeah, it'll probably be called a lunchbox, and there are definitely some features I could add that would really reduce tedium as well, like being able to right click an inventory with it to auto-fill it with an intelligently chosen variety of foods form the inventory (e.g. foods that aren't diminished + variety of hunger values), or being able to 'eat' the lunchbox to intelligently eat a food inside (e.g. choosing the food that is least diminished + would least overfill your hunger bar).
> After thinking about it some more, it's pretty much certain that some sort of lunchbox item will be added.

**Comment by bonii-xx** [comment]
Don't forget to rename it to "Happy Meal" if it contains the correct contents.

**Comment by squeek502** [comment]
More like unhappy meal, am I right?
