### ISSUE TITLE
Tooltip glich or bug

### ISSUE THREAD

**Issue by kikisp** [squeek502/SpiceOfLife#26]
I keep getting  on all my foods  tooltip not eaten recently but  when i eat them  i get diminishing returns..
i think that tooltips are somehow getting corrupted.They are not showing history of foodsI am using 1.1.1 version on 1.7.10.
Sorry for not explaining it nicely but i hope that you understand what i mean

**Comment by Arkandos** [comment]
I can confirm this. Using the foodjournal updates the tooltip to it's correct value.

**Comment by squeek502** [comment]
Give me as much information as you possibly can.

Single player or on a server?
If it's a server, is it running Cauldron?

**Comment by Arkandos** [comment]
Server, not using Cauldron

Forge: 10.13.0.1208
Spice of life: 1.1.1

**Comment by kikisp** [comment]
For me is ssp.. 
hey arkandos do you run botania or ee3 maybe? when i updated botania and removed dev build off ee3..spice of life started working like it shuold. but only on new world creation...

**Comment by squeek502** [comment]
From [my post about this on the MCF forums](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2091809-the-spice-of-life-encouraging-dietary-variety?comment=226):

> If food.history.length is >= new.player.food.eaten.threshold, clear.history.after.food.eaten.threshold.reached is true, and a player's food history has more than new.player.food.eaten.threshold foods in it, the client will incorrectly reset the food history while it is being populated with the server's values.
