### ISSUE TITLE
Add support for GregTech drinks

### ISSUE THREAD

**Issue by squeek502** [squeek502/SpiceOfLife#27]
From [here](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2091809-the-spice-of-life-encouraging-dietary-variety?comment=139)

> Finally playing with SoL in our 1.7 custom pack. Gregtech has a way of making bottled drinks, but they have no diminishing returns. For example, he has a 'Purple Drink' that gives 3 hunger and 1.5 saturation (and slowness debuff)...but has no dim returns. Wonder if there is anything that can change/fix this on your side.

**Comment by Kehaan** [comment]
Oh just made a post about that on the Minecraft forum.

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2091809-the-spice-of-life-encouraging-dietary-variety?comment=145

Have the issue too. Using GregTech and SpiceOfLife for Minecraft 1.6. I would love if the Purple Drink could be added to SpiceOfLife :)

**Comment by Kehaan** [comment]
I find the Purple Drinks as dungeonloot, so its alittle OP to get that, where SpiceOfLife those not recognize it.

**Comment by squeek502** [comment]
Closing. This is no longer an issue in 1.7.10 and I've finally started dropping support for 1.6.4.
