### ISSUE TITLE
Translation to Spanish

### ISSUE THREAD

**Issue by crissto** [squeek502/SpiceOfLife#34]
I don't know where I can put this, sooo.. Here you have it. A translation from your mod to Spanish.
https://www.dropbox.com/s/ln27y88dk3zob72/Spice%20of%20Life.txt?dl=0

**Comment by squeek502** [comment]
Thanks!

If you want to contribute it yourself, go [here](https://github.com/squeek502/SpiceOfLife/tree/master/resources/assets/spiceoflife/lang) and then click the **+** next to `SpiceOfLife / resources / assets / spiceoflife / lang /` at the top. Name the file `es_ES.lang` (or [the appropriate Spanish locale](http://www.localeplanet.com/java/)) and then submit a pull request.
