### ISSUE TITLE
Doesn't seem to respect the "affect.food.hunger.values=false"

### ISSUE THREAD

**Issue by Xandermud** [squeek502/SpiceOfLife#43]
I was attempting to set the configs to only affect saturation and it seems to just ignore it. 
the only configs I changed were:
affect.food.hunger.values=false
affect.food.saturation.modifiers=true

Eating a grilled cheese from HarvestCraft normally grants 9 hunger and 20 saturation (without hunger overhaul). After eating one, the new values are 4 hunger and 5 saturation. I've tested it with many different foods from vanilla and HarvestCraft with similar results. It would seem that hunger is diminishing regardless and saturation is dropping twice as fast.

Mods installed:
AppleCore-mc1.7.10-1.0.0
Pam's HarvestCraft 1.7.10c
SpiceOfLife-mc1.7.10-1.2.2
Forge 10.13.2.1232

**Comment by squeek502** [comment]
Thanks for reporting this. I seem to have messed up while porting those changes to the 1.7.10 version and left that out. Will fix in a bit.

**Comment by squeek502** [comment]
Fixed by 58cb0d42b7e9b1b90efa89a84085dcee49cfaabc. Will be fixed in the next version.
