### ISSUE TITLE
TC Manabean bug

### ISSUE THREAD

**Issue by MrHohenheim** [squeek502/SpiceOfLife#49]
Hello

I use RR modpack and if i have your spice of life mod i cant plant manabeans. "always want to eat them"  i know i think how to solve this problem , default whitelist the manabean maybe? becuse idk how to add this for black/whitelist for ignore manabean becuse this not a food.

**Comment by squeek502** [comment]
What version of Minecraft? Are you sure you're trying to plant them in a magical biome? From the [TC wiki](http://thaumcraft-4.wikia.com/wiki/Mana_Beans):

> can only be grown in magical biomes

**Comment by MrHohenheim** [comment]
SPICEOFLIFE-MC1.7.10-1.2.3.jar

1.7.10 and Resonant Rise  3.2.1.0 pack

yes  magical biome and bottom of log

**Comment by squeek502** [comment]
Will look into it.

**Comment by MrHohenheim** [comment]
we solved the problem,

**Comment by squeek502** [comment]
What was the problem?

**Comment by MrHohenheim** [comment]
The Human stupidity... iam the server owner and i asked 2 times how to used the manabeans and others tell me whats the problem , and my bad i not tested ...
