### ISSUE TITLE
Unaffected Foods

### ISSUE THREAD

**Issue by GodricSeer** [squeek502/SpiceOfLife#50]
I have found that vanilla mushroom stew is not affected by SpiceOfLife.  I am using SpiceOfLife-1.7.10-1.2.3 in the EthoLP modpack, with default configurations.  The stew  is not recorded in the food journal, not affected by diminishing returns, and not pulled out of chests by a lunchbag (and I'm assuming lunch box).

**Comment by squeek502** [comment]
Not able to reproduce with just AppleCore + TSoL; everything works perfectly fine. 

Perhaps some mod is overwriting mushroom stew?

**Comment by GodricSeer** [comment]
I restarted the game and it resolved itself.  The logs from the problematic run were cleared at that time, so if it happens again I will attach them to see if there was some error in loading.

**Comment by GodricSeer** [comment]
By messing around in creative I found that it is the Natura mushroom stew that is the problem.  Pulling vanilla minecraft stew from the creative menu works as intended with TSoL.  Using a bowl and mushrooms to create the stew creates the Natura version which is then not tracked by TSoL.  This might just be a compatibility issue between the mods.

Edit: Natura version 1.7.10-2.2.0.1

**Comment by squeek502** [comment]
Ah, that _should_ be fixed, but it looks like Natura hasn't released a new version with the fix yet.

See: https://github.com/progwml6/Natura/issues/207
