### ISSUE TITLE
Weird interaction with MineFactory Reloaded

### ISSUE THREAD

**Issue by Thistlebalm** [squeek502/SpiceOfLife#51]
This is with MineFactoryReloaded-[1.7.10]2.8.0RC7-71, SpiceOfLife-mc1.7.10-1.2.3, and AppleCore-mc1.7.10-1.1.0

When right-clicking a MFR conveyor belt with an open lunch box/bag the food spills out.

Nothing major, just thought I might report the seemingly odd behavior :)

**Comment by squeek502** [comment]
Weird indeed. Thanks for reporting it.
