### ISSUE TITLE
food journal not reset

### ISSUE THREAD

**Issue by Kenshij** [squeek502/SpiceOfLife#52]
Hello,

i have the problem that my food jurnal is not reseting. I'm eating out of a lunchbox MRE food from abysalcraft which gives twice the hunger bar and have eaten 3 different sandwitches. Normally after the sandwitches my food should reset or after i eat two times the MRE but nothing. I have crafted the food jurnal and all foods are shown there.
![food_issue](https://cloud.githubusercontent.com/assets/11033477/6586766/91bbea7a-c77c-11e4-9b77-94bbdd2c2acb.png)

**Comment by squeek502** [comment]
What does the tooltip on the MRE say?

**Comment by Kenshij** [comment]
MRE
Feast
Nutrition Value: something by 25%
Eaten 3 times out of the last 12 Food
Abysalcraft
Food meter same like in the journal

**Comment by squeek502** [comment]
The food history works as a [queue](http://en.wikipedia.org/wiki/Queue_%28abstract_data_type%29), meaning that foods only get removed from it once the queue is full. So, to remove the first MRE you ate from the history, you'd have to eat 7 more foods (6 more to fill the queue and then the 7th to bump the first MRE off the list).

Closing as this does not seem to be a bug.
