### ISSUE TITLE
[Request] Config option to turn off SOL tooltip for Rotten Flesh (For Mekanism/Vending Machines/Other Tech Mods) 

### ISSUE THREAD

**Issue by MFernflower** [squeek502/SpiceOfLife#54]
Certain mods seem to not like when SOL adds a tooltip to zombie flesh. A config option to turn that off for zombie flesh might be what I need.

**Comment by Scratchman** [comment]
Just to clarify the issue, this crash seems to be a conflict with gui's between the spice of life mod and the [vending blocks mod](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2332709-vending-block). 

When a player places any edibles in a vending block and then places their cursor over the vending block the player is disconnected and can't connect to the server again until the spice of life info is wiped form their player.dat. We do that by temporarily disabling the SOL mod on the server, then have the players reconnect to wipe the SOL information from thier player.dat.

crash report from the client, http://pastebin.com/NbwPy29v

**Comment by squeek502** [comment]
Seems like [this commit](https://github.com/kamilx3/VendingBlock/commit/5fa6607772e65202b198322be2a9828979a3e15c) fixed it.

Can you check to see if this still occurs with the latest version of Vending Block?

**Comment by squeek502** [comment]
@MFernflower can you clarify what the issue is with Mekanism?

**Comment by MFernflower** [comment]
Seems like everything is fixed. It was the interatcion of mek and vendingblock.

**Comment by Scratchman** [comment]
Just tested out Spice of Life with the latest version of the Vending block mod and their update seems to have fixed the issue. Looks like i'm not the first one to come across the problem. Thanks for the great mod. Our server community appreciates all the time and effort you put into developing your mods.

https://www.dropbox.com/s/yienadk9xc8b9lr/2015-04-16_18.24.37.png?dl=0
