### ISSUE TITLE
Conflict bewteen Vending Machines Mod and Spice of Life

### ISSUE THREAD

**Issue by MFernflower** [squeek502/SpiceOfLife#55]
When inserting rotting flesh into the sell or buy slot of a vender block this happens: http://pastebin.com/GnEBbaHa and will happen to any player who approaches the block

**Comment by squeek502** [comment]
Duplicate of #54? Updating Vending Block should fix it.

**Comment by MFernflower** [comment]
Keeping this open until server admin updates modpack and can verify it is working.

**Comment by MFernflower** [comment]
Seems to be fixed.
