### ISSUE TITLE
Request: New formula variables "hunger_count", "saturation_count"

### ISSUE THREAD

**Issue by copygirl** [squeek502/SpiceOfLife#58]
With my other issue reported and there being the possibility of another release soon, I thought I'd try to drop this suggestion as well. Here's my current food formula:

```
MAX(0, MIN(1, 1.5 - (count*food_hunger_value)/40))
```

What I was going for is creating a system where the nutrition factor goes down after eating a certain amount of food (in actual hunger points restored). My current approximation (`count*food_hunger_value`) breaks down when switching between foods from the same food group that have different hunger values.

Therefore I'd like to suggestion two more variables that track the amount of hunger and saturation restored in the current history for the food item / food group.

**Comment by squeek502** [comment]
Yeah, sorry, this has been requested for a long time (see #44) but I haven't gotten around to it. Will definitely make sure to get it done before the next version.

**Comment by copygirl** [comment]
Well, I remembered something, and did check the issues before, but somehow I decided that one's title didn't have anything to do with this. Derp.
