### ISSUE TITLE
[Suggestion] Reverse keys to open 

### ISSUE THREAD

**Issue by xenoflot** [squeek502/SpiceOfLife#59]
Hi Squeek,

I'm playing with your mod for the first time. I find that right click opens the lunchbox so I can refill it and I need to shift-right click to "open" it for eating. That seems counter-intuitive to me, although I see that an unshifted right click would conflict between opening it eat and actually eating.

Having to open your lunchbox is a nice feature; is it possible to capture left click for open/close so that right click is free for eating?

If not, perhaps use ctrl+right click for filling, or add a config option to set to "dull and boring mode" such that shift-click opens for filling and right-click is just eat.

**Comment by squeek502** [comment]
I'm not sure there's a _good_ solution to this. The problem with left click is that it has a very consistent purpose, and overriding that might be confusing. Making it an option might not be a problem, though.

**Comment by xenoflot** [comment]
You're right, however I think people would pretty quickly get the message when they go to punch someone with their lunchbox and it opens instead. :-)
