### ISSUE TITLE
Diminishing returns blacklist problem

### ISSUE THREAD

**Issue by Ionaru** [squeek502/SpiceOfLife#61]
When adding items to the diminishing returns blacklist using the .json files, it only removed the tooltip for the food items, not the actual calculations.

My .json file: http://pastebin.com/Hx6rkurf
Screenshot after eating the food:
![2015-08-07_23 24 38](https://cloud.githubusercontent.com/assets/3472373/9146361/6d4c889c-3d5c-11e5-8b95-4177f813604a.png)

Am I doing something wrong or is this a real problem?

Using:
- Forge 10.13.4.1481
- Applecore 1.1.0
- SpiceOfLife 1.2.3
- Harvestcraft J

The issue also occurs without any extra mods installed, besides the ones listed above and NEI.

**Comment by squeek502** [comment]
Interesting, sounds like a real issue. Will take a look, thanks for reporting it.

**Comment by squeek502** [comment]
Yeah, I totally messed that up. The only place I check if a food is blacklisted is in the tooltip handler. Whoops!

Will fix.

**Comment by Ionaru** [comment]
Thanks!
Do you have any idea when this new version will be released?

**Comment by squeek502** [comment]
Was planning on releasing a new version soon anyway, so I'll release once I get this fixed.

**Comment by squeek502** [comment]
https://github.com/squeek502/SpiceOfLife/releases/tag/v1.2.4
