### ISSUE TITLE
IndexOutOfBoundsException using Food Journal

### ISSUE THREAD

**Issue by Dulciphi** [squeek502/SpiceOfLife#63]
Apologies if this due to inv tweaks or user error. 

I was trying to teach my son how Spice of Life works.. opened up the food journal to show him food history ...and crashed. I usually don't use the journal, sorry, so I'm not sure if this is an old issue or even unrelated to SoL. I found it reported on your [MCF thread](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2091809-the-spice-of-life-encouraging-dietary-variety?comment=278) but it seemed to go unnoticed ..so I'm bugging you with it here. Hope you don't mind.

[snip of log with crash](http://pastebin.com/rzKZHbBA)

Thank you

**Comment by squeek502** [comment]
Thanks for reporting it. Unfortunately, it's very difficult for me to debug it because I haven't found a way to reproduce it and it has something to do with vanilla code syncing the container slots to the client.

If it happens consistently for you, could you perhaps send me your entire Minecraft instance folder (world + mods + config)?

**Comment by plazia** [comment]
I had a fully functioning modpack I've been using for some 300 odd (minecraft) days. I installed Spice of life to try it out. Opened the food journal for the first time, clicked the up arrow in the GUI and instacrash with "shutting down server" playing in single player. (I realise it runs a server internally) 

While the crash report doesn't specifically cite Spice of life it is the only mod I was interacting with at the time of the crash and all else seems to be working fine.

Crash report here: http://pastebin.com/jx238bZ7

**Comment by Sirse** [comment]
Same problem exist for me.
http://pastebin.com/shAD3403
Thermos server, 1.7.10
Crash only on client, server works fine.

**Comment by squeek502** [comment]
Finally figured out whats causing this: picking up an item while in the food journal screen. Will have a fix soon.

**Comment by squeek502** [comment]
Fixed in v1.3.8: https://github.com/squeek502/SpiceOfLife/releases/tag/v1.3.8
