### ISSUE TITLE
is there a way to add unaffected food sources to spiceoflife?

### ISSUE THREAD

**Issue by canilsen** [squeek502/SpiceOfLife#64]
Currently, Glowing Bread from Xeno's Reliquary isn't giving diminishing returns. Is there a way to add it in via configs? Tooltip says "Light Meal" and "Not eaten recently".

**Comment by squeek502** [comment]
That mod will have to fix their implementation. See: https://github.com/squeek502/AppleCore/wiki/Integrating-food-items-with-AppleCore
