### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException when R-Click with Food Container of different storages

### ISSUE THREAD

**Issue by joye-ramone** [squeek502/SpiceOfLife#67]
Hi,

I am getting from to time java.lang.ArrayIndexOutOfBoundsException: 6 when (by mistake) R-Client on different storage/containers (chest, barrels, machines) with Food Container.

See logs:
http://pastebin.com/Yi4HsgHG
http://pastebin.com/3pbL8NLV

This happens to all times, but pretty often.
Could you please take a look and fix this is possible?

**Comment by squeek502** [comment]
Thanks for reporting. I think I know what might be happening--will confirm and fix this when I get the chance.
