### ISSUE TITLE
Crash with Version 1.3.0

### ISSUE THREAD

**Issue by Dream-Master** [squeek502/SpiceOfLife#68]
I get this Crash. (Version 1.3)
https://gist.github.com/Dream-Master/71303695fda1d6a370bf#file-sol

**Comment by squeek502** [comment]
Looks like some core mod is misbehaving. Did version 1.2.4 work fine?

I'm unable to reproduce this with just AppleCore + The Spice of Life.

**Comment by Dream-Master** [comment]
Yes Version 1.2.4 runs fine.

**Comment by Dream-Master** [comment]
I am running it in a Modpack.

**Comment by squeek502** [comment]
There was only [a single change](https://github.com/squeek502/SpiceOfLife/blob/236eb9d453f58827129cae9de014d7aa52970b95/java/squeek/spiceoflife/ModSpiceOfLife.java#L74) in the `ModSpiceOfLife` class between 1.2.4 and 1.3.0, and that was the renaming of a function call, so I really don't know what could be causing this.

Not sure how to debug it, as I can't reproduce it. I get no errors with SoL 1.3.0 and Optifine together, either.

**Comment by squeek502** [comment]
What modpack are you using? Is it public?

**Comment by Dream-Master** [comment]
No its a privat one.

_Deleted links_

Please delete the link after downloading.

**Comment by squeek502** [comment]
Still unable to reproduce the crash with the modpack + SoL 1.3.0. Try redownloading SoL v1.3.0, maybe? Could have gotten a corrupted file?

https://github.com/squeek502/SpiceOfLife/releases/tag/v1.3.0

**Comment by Dream-Master** [comment]
Will Try tomorrow. Thanks for your help.

**Comment by Dream-Master** [comment]
Error is gone using the same File. Not sure why it crash before.
