### ISSUE TITLE
Resizing Game Window adds fake entries to food journal

### ISSUE THREAD

**Issue by UndeadZeratul** [squeek502/SpiceOfLife#69]
Spice of Life v1.3.0
Forge v1448
Apple Core v1.1.0

Nothing critical, but I noticed that when I maximized my game window, then un-maximized it, then maximized it again, there would be extra entries in my food journal.  When I close and open the book, however, they go away and show the correct entry.

When First (and Re-)Opened:
![First Image](https://i.imgur.com/vGAB7x5.png)

After Un-Maximizing
![Second Image](https://i.imgur.com/yNPewzG.png)

After Re-Maximizing
![Third Image](https://i.imgur.com/nyGxqUk.png)

**Comment by squeek502** [comment]
Thanks for reporting this. I ran into it when testing but didn't realize what caused it and thought it was a fluke.

**Comment by UndeadZeratul** [comment]
Yeah I ran into it on accident from alt-tabbing and whatnot and saw that I had more than one, when I only ate one thing, I kept doing it and it kept getting added, until I closed and re-opened the book.  Seems to only be visual, so that's good.

**Comment by squeek502** [comment]
This may have actually been a long-standing bug and might also be the cause of https://github.com/squeek502/SpiceOfLife/issues/63
