### ISSUE TITLE
Some suggestion for hunger/saturation buffs/debuffs

### ISSUE THREAD

**Issue by ghost** [squeek502/SpiceOfLife#71]
I received a couple suggestions from my modpack team, which seemed like good ones.

First, if a player eats something with a high hunger satisfaction value (high-tier recipes from Pam's, for example), there should be some kind of buff supplied to the player, as a way to encourage the use of higher-tier recipes, instead of just eating a bunch of crops and calling it a meal.

Second, a stomachache status from maxing out the saturation meter, thereby debuffing the player for a specific time, during which, the hunger/saturation bar doesn't diminish.  Once the debuff time expires, the saturation value can optionally drop or disappear altogether.  Think of it as a way to prevent greed. ;)

**Comment by squeek502** [comment]
1. What type of buff would you suggest?
2. Not sure about this one. Don't think it fits with the mod, and saturation has some quirks to it that would make it function rather strangely (e.g. saturation can never exceed the current hunger of the player). Saturation also differs wildly between foods, and, for example, _many_ HarvestCraft foods max out saturation on their own when not using Hunger Overhaul.

**Comment by ghost** [comment]
Hmmm... On initial blush, I would probably say something like the opposite of HO starvation status effects... probably something like strength, or haste (mining).

Although now that you mention it, this might be more appropriate for HO than SoL.

**Comment by ghost** [comment]
For now, I'm going to close this until I've thought more about the issue, which buffs would be best, and which mod would best handle the situation.
