### ISSUE TITLE
Translation text problem

### ISSUE THREAD

**Issue by XuyuEre** [squeek502/SpiceOfLife#77]
When I update the zh_CN translation text ,I find a Translation text problem.
for example`<spiceoflife.tooltip.eaten.recently=Eaten %s out of the last %d foods>` (English),I translate into Chinese is `<spiceoflife.tooltip.eaten.recently=之前食用的%d个食物中,它占了%s>`.BUT in the game  I see the tooltips ,the display of the variable is wrong.Such as Chinese and other need to change the order of language .It will result in an abnormal translation, unless it is translated by a statement that is not in accordance with Chinese language habits. Please see the pictures here：http://i4.tietuku.com/3d748dbb5bab5d6b.png  and  http://i4.tietuku.com/bcb4f4e4ecca375c.png

**Comment by squeek502** [comment]
Try this:

```
spiceoflife.tooltip.eaten.recently=之前食用的%2$d个食物中,它占了%1$s
```
