### ISSUE TITLE
Hungry reset on dimension change - Server

### ISSUE THREAD

**Issue by SrAnthony** [squeek502/SpiceOfLife#80]
When a cracked player teleports to another dimension occurs a hungry reset.

Video: https://www.youtube.com/watch?v=SsolN3ltVQ8

Using latest Spice of Life version with KCauldron (Thermos).

**Comment by squeek502** [comment]
This would be an incompatibility between KCauldron and [AppleCore](https://github.com/squeek502/AppleCore). AppleCore is _not_ compatible with KCauldron, unfortunately.

Moving this to https://github.com/squeek502/AppleCore/issues/46
