### ISSUE TITLE
Issue when trying to set use.time.for.food.history.length as true

### ISSUE THREAD

**Issue by nickolasdeluca** [squeek502/SpiceOfLife#83]
I'm setting up a server to play with some friends, and I was trying to set time to define the deminishing values, and the server goes online just fine, but when I try to log in, I get this error, and the same happens to everyone:
**java.lang.ClassCastException: squeek.spiceoflife.foodtracker.foodqueue.FixedHungerQueue cannot be cast to squeek.spiceoflife.foodtracker.foodqueue.FixedTimeQueue**

I have already tried to reset everyone's history and then stopping the server and changing the config file but the same error occurs.

If any of you can point out the mistake I'm making, I would be very pleased.
Btw, nice mod.

Edit: modpack version on server is 1.2.4, Blightfall modpack on technic.

**Comment by squeek502** [comment]
Thanks for reporting. Can you post a bit more of the crash log? You can paste the whole thing into somewhere like http://pastebin.com and then post the link here.

**Comment by nickolasdeluca** [comment]
I think this is what you want...
http://pastebin.com/XRnYA22h
The problem is that the server doesn't crash itself, neither my client crashes, but the it shows an "Internal Server Error" and kicks me out of the server...
Let me know if you need anything else

**Comment by squeek502** [comment]
That's exactly what I wanted, thanks. Will look into it.
