### ISSUE TITLE
Constant hunger

### ISSUE THREAD

**Issue by Ganjalf-Amsterdoom** [squeek502/SpiceOfLife#85]
Hello,

pardon to bother for this small problem but I remember there was a config to disable this but I can't find it. I'm getting hunger even if I don't move, like permanent constant hunger. How do I enable hunger loss only when I actually move?

Thank you for your time.

**Comment by squeek502** [comment]
This is likely from Hunger Overhaul, not The Spice of Life. See the config option `constantHungerLoss` in the Hunger Overhaul config.

**Comment by Ganjalf-Amsterdoom** [comment]
I don't have HoH... only spice of life and applecore... could it be some other mod? I will investigate.
Thank you for the quick reply

**Comment by squeek502** [comment]
Yes, it is some other mod. The Spice of Life does not modify how exhaustion works. AppleCore does not make any modifications on its own, either (see [AppleCore features](https://github.com/squeek502/AppleCore/wiki/AppleCore-features)).

**Comment by Ganjalf-Amsterdoom** [comment]
Thank you and again pardon to have bodered

**Comment by squeek502** [comment]
No worries :smile:. It can be frustrating trying to figure out what mod is doing something unexpected. Hope you can figure it out.
