### ISSUE TITLE
1.9 release?

### ISSUE THREAD

**Issue by Gaelan** [squeek502/SpiceOfLife#89]
Is there anything that needs to happen before SoL is released for 1.9? It looks like there is a ported branch, but there aren't downloads on CF. Are there still bugs/missing features?

**Comment by squeek502** [comment]
I think it might be ready. Planning on releasing it today.

**Comment by Gaelan** [comment]
Good, thanks!

**Comment by squeek502** [comment]
https://github.com/squeek502/SpiceOfLife/releases/tag/v1.3.2
