### ISSUE TITLE
[1.10.2] Lunchbox missing texture when opened

### ISSUE THREAD

**Issue by Carrots4U** [squeek502/SpiceOfLife#93]
In the latest version of Spice of Life for version 1.10.2 of Minecraft, when you open the lunchbox, the texture turns into the typical black & purple checker pattern. Closing it makes it return to normal

http://i.imgur.com/tPcBeLd.png

**Comment by squeek502** [comment]
Interesting, wonder what changed between 1.9.4 and 1.10.2. Appreciate the report, will look into it.

**Comment by squeek502** [comment]
Can't reproduce this with the latest Forge and no other mods present. Try updating Forge and see if that fixes it for you.

**Comment by Carrots4U** [comment]
We are running the latest Forge also. I'm guessing it is some weird mod interaction then?

**Comment by squeek502** [comment]
Might be, could you post a mod list?

**Comment by Carrots4U** [comment]
AbyssalCraft (by Shinoow)
Actually Additions (by Ellpeck)
Advanced Generators (by bdew)
AppleCore (by squeek502)
ArmorPlus (by sokratis12GR)
Aroma1997Core (by Aroma1997)
AromaBackup (by Aroma1997)
AtomicStryker's Infernal Mobs (by AtomicStryker)
AutoPackager (by smbarbour)
Bagginses (by lorddusk)
Baubles (by azanor)
BdLib (by bdew)
Better Agriculture (by koxhack)
BetterBedrockGen (by Gigabit1011)
BetterFps (by Guichaguri)
Biomes O' Plenty (by Glitchfiend)
Blood Magic (by WayofTime)
Bloodmoon (by lumien231)
Bookshelf (by darkh4x)
Botania Unofficial (by williewillus)
Bullseye (by Glitchfiend)
Calculator (by Ollie_Lansdell)
Chameleon (by jaquadro)
Charset (by Vazkii)
Chisel (by tterrag1098)
Chisels & Bits (by AlgorithmX2)
Cooking for Blockheads (by Blay09)
Correlated Potentialistics (by Aesen)
Crafting Tweaks (by Blay09)
CraftTweaker (by jaredlll08)
Custom Main Menu (by lumien231)
Dark Utilities (by darkh4x)
Deep Resonance (by McJty)
DrCyano's Ore Spawn (by Cyanobacterium)
Easy Breeding (by anthonysheets)
ElecCore | Rendering Library (by Elec332)
End Metals (by jriwanek)
Ender IO (by CrazyPants_MC)
Ender Zoo (by CrazyPants_MC)
EnderBags (by Gigabit1011)
EnderCore (by tterrag1098)
EnderTanks (by ShetiPhian)
Enderthing (by gigaherz)
Environmental Tech (by ValkyrieofNight)
Experience Rings (by MrComputerGhost)
Extra Utilities (by RWTema)
Fast Leaf Decay (by lumien231)
Flat Colored Blocks (by AlgorithmX2)
Forestry (by SirSengir)
Gendustry (by bdew)
Giacomo's Fishing Net (by Zacomat)
Grapple Hooks (by Kloonder)
Inventory Tweaks (by Kobata)
Iron Chests (by progwml6)
Item Scroller (by masa_)
JourneyMap (by techbrew)
Just Enough Items (JEI) (by mezz)
Just Enough Resources (JER) (by Way2muchnoise)
Mantle (by mDiyo)
McJtyLib (by McJty)
MCMultiPart (by amadornes)
MmmMmmMmmMmm (by bonusboni)
More Overlays (by feldim2425)
Morpheus (by quetzi)
Morph-o-Tool (by Vazkii)
Nashorn Scripting Library (by TarynWinterblade)
Nether Metals (by koxhack)
NetherPortalFix (by Blay09)
No Mob Spawning on Trees (by oldjunyi)
Not Enough Wands (by romelo333)
OpenComputers (by Kethtar)
OreDictionaryConverter (by EXTER7)
Packing Tape (by gigaherz)
Pam's HarvestCraft (by MatrexsVigil)
Pillar (by Vazkii)
Platforms (by ShetiPhian)
Progressive Automation (by VanhalMinecraft)
Psi (by Vazkii)
Quark (by Vazkii)
Random Things (by lumien231)
Refined Storage (by raoulvdberge)
Reliquary v1.3 (by P3pp3rF1y)
Resource Loader (by lumien231)
RFTools (by McJty)
RFTools Dimensions (by McJty)
Roguelike Dungeons (by Greymerk)
Roots (by elucent)
Rough Mobs (by Lellson)
ShadowMC (by shadowfactsmc)
ShetiPhianCore (by ShetiPhian)
ShieldHider (by big_Xplosion)
SimpleHarvest (by TehNut)
Simpleretrogen (by cpw11)
Sleeping Bag (by shadowfactsmc)
Solar Village (by darkh4x)
Sonar Core (by Ollie_Lansdell)
Soul Shards: The Old Ways (by SgtPunishment)
Storage Drawers (by jaquadro)
Substratum (by EXTER7)
TESLA (by darkh4x)
The One Probe (by McJty)
The Spice of Life (by squeek502)
Tinkers Construct (by mDiyo)
Tomb Many Graves (by M4thG33k)
UniDict (by WanionCane)
ValkyrieLib (by ValkyrieofNight)
ViesCraft (by Viesis_Gaming)
Water Strainer (by Rubironi)
WeaponsPlus (by sokratis12GR)
WIT (What Is That) (by SilentChaos512)

We've removed Mekanism, Water Strainer, Viescraft, Fishing Nets, Gendustry, or Reliquary and tested it, so it's not those mods for sure.

**Comment by Carrots4U** [comment]
We are testing in what update it started in, and comparing modlists to see what mods we updated/changed in order to narrow it down.

**Comment by squeek502** [comment]
Could you set up a new instance with only The Spice of Life and AppleCore and see if you get the same issue? Make sure to use the same .jar file if possible (to test if it's the file itself that's the problem).

**Comment by Carrots4U** [comment]
The issue does not occur with only SoL & Apple Core.

**Comment by Carrots4U** [comment]
We have narrowed it down to these mods, they are the only ones updated when the issue began.

ActuallyAdditions-1.10.2-r49
craftingtweaks-mc1.9.4-5.0.6
ironchest-1.10.2-7.0.6.794
jei_1.10.2-3.7.5.227
Quark-beta-40
rftools-1.10-5.02
roots-0.107
Substratum-1.10.2-1.6.0.1
theoneprobe-1.10-1.0.13

**Comment by squeek502** [comment]
Interesting, thanks for narrowing it down. I'll see if I can reproduce it when I get a chance.

**Comment by Carrots4U** [comment]
We have our players testing it now too, hopefully we can figure it out :smile:

**Comment by Carrots4U** [comment]
Okay this is very weird, we have narrowed it down to our Reliquary Config. If we remove it and make it create a new one the texture is normal. The only thing we changed in the config is disabling the Alkahestry Tome.

**Comment by squeek502** [comment]
Very strange, sounds like a bug in Reliquary, then. In taking a quick look at the Reliquary code, my suspicion is that it is still registering the icons for the tome even though the item is not being registered.

For example, there's this check here when it registers the item and ItemBlockModels:
- https://github.com/P3pp3rF1y/Reliquary/blob/22c95cde5bca1cc82f2fd53dcf5271238171ec56/src/main/java/xreliquary/init/ModItems.java#L220-L221
- https://github.com/P3pp3rF1y/Reliquary/blob/22c95cde5bca1cc82f2fd53dcf5271238171ec56/src/main/java/xreliquary/client/init/ItemBlockModels.java#L28-L29

But it's missing when it's registering ItemModels:
- https://github.com/P3pp3rF1y/Reliquary/blob/22c95cde5bca1cc82f2fd53dcf5271238171ec56/src/main/java/xreliquary/client/init/ItemModels.java#L129-L141

I'm not exactly certain how that could be causing this issue, but it seems likely that it is given the methods to reproduce it.

**Comment by Carrots4U** [comment]
Thank you for your help! I know it's not your mod's bug but thanks for the help! I will report the bug to the Reliquary Developer, and until then I'll just disable the Tome's recipe using CraftTweaker. Thanks for the help & your great mod!
