### ISSUE TITLE
Missing textures for open (full and empty) lunchbox and lunchbag as well as food journal

### ISSUE THREAD

**Issue by ghost** [squeek502/SpiceOfLife#94]
The texture for the lunch box and bag are okay but opening them will turn them into the checkered purple and black missing texture. The food journal also displays as a missing texture.
This can be reproduced by using the Spice of Life with the mod EnderIO

Spice of Life version 1.3.3 for MC 1.10.2
Apple Core version 1.3.5 for MC 1.10.2
EnderIO version 3.0.1.75 for MC 1.10.2
EnderCore version 0.4.1.41 for MC 1.10.2

If this should be discussed with the author of EnderIO instead, sorry and I will get on that.

**Comment by squeek502** [comment]
Thanks for reporting this, [a similar issue with Reliquary](https://github.com/squeek502/SpiceOfLife/issues/93) also seems to exist. I'll double check that I'm doing everything correctly when registering the textures.

It only happens when EnderIO is installed, correct?

**Comment by ghost** [comment]
It seems to only be EnderIO. I tested it with about 15 other 1.10 mods and it worked fine. EnderIO has some features that render weird stuff so I'm not surprised.

**Comment by squeek502** [comment]
Moving this to #100
