### ISSUE TITLE
Food from a specific mod isn't being tracked

### ISSUE THREAD

**Issue by lOmicronl** [squeek502/SpiceOfLife#96]
I've been using Spice of Life, made myself several custom food groups, tweaked the nutrition value formula to my likes, and so on and so forth. Modded food works just fine - for example berries from Biomes o'Plenty, or tree produce from Forestry.

Today I added the [Food Expansion](https://minecraft.curseforge.com/projects/food-expansion?gameCategorySlug=mc-mods&projectID=235328) mod. I went and added all of the edible items to my custom food groups, like I did with everything else. Ingame, the items tooltips list the food group correctly, as well as the current nutritional value if the food if this food group was eaten recently. Pressing shift correctly produces the AppleCore display of how much hunger it restores, including the reddened out bits if nutritional value is less than 100%.

So far, so good.

But when I eat something - anything - added by this mod, it is not tracked in my food journal, and it does not modify the food group's nutritional value. It's as if I never ate it... but it definitely restores my hunger. Any idea what could be the cause? Need anything supplied to help narrow it down?

**Comment by squeek502** [comment]
Sounds like their food overrides onItemUseFinish and calls the wrong FoodStats method.

Direct the mod author to: https://github.com/squeek502/AppleCore/wiki/Integrating-food-items-with-AppleCore

**Comment by squeek502** [comment]
Commented on the Food Expansion CurseForge page here: https://minecraft.curseforge.com/projects/food-expansion?comment=12
